name: phpunit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.2', '7.3', '7.4']
        neo4j-versions: ['3.3', '3.4', '3.5', '4.0', '4.1']
        include:
          - neo4j-versions: 3.3
            bolt-version: 1
          - neo4j-versions: 3.4
            bolt-version: 2
          - neo4j-versions: 3.5
            bolt-version: 3
          - neo4j-versions: 4.0
            bolt-version: 4
          - neo4j-versions: 4.1
            bolt-version: 4
    services:
      neo4j:
        image: neo4j:${{ matrix.neo4j-versions }}
        volumes:
          - ${{ github.workspace }}/.certificates:/ssl
        env:
          NEO4J_AUTH: none
          NEO4J_dbms_ssl_policy_bolt_enabled: true
          NEO4J_dbms_connector_bolt_tls__level: OPTIONAL
          NEO4J_dbms_ssl_policy_bolt_base__directory: /ssl/bolt
        ports: 
          - 7687:7687
    steps:
    - uses: actions/checkout@v2

    - name: Wait for neo4j to fail
      run: while docker ps | grep neo4j ; do sleep 2 ; done
      
    - name: Restart neo4j
      run: docker start ${{ job.services.neo4j.id }}
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
      
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest
    
    - name: Lint
      run: composer lint
    
    - name: Wait for neo4j to be ready
      run: until docker exec ${{ job.services.neo4j.id }} wget -q -O - localhost:7474 > /dev/null ; do sleep 2; done 
    
    - name: Test
      env:
        BOLT_VERSION: ${{ matrix.bolt-version }}
      run: composer test
    
    - name: Coverage
      uses: codecov/codecov-action@v1

   
